Repository gisce/primestg, pull requests merged in 2021-03, with the labels that each got.

#57 Arreglar _get_timestamp de ValueWithTime
  primestg/report/base.py
Labels: bug, to be merged

#64 New b12 power change
  primestg/cli.py
  primestg/dlms_templates.py
  primestg/order/orders.py
  primestg/utils.py
  setup.py
  spec/Order_B12_spec.py
  spec/utils_spec.py
Labels: deployed, enhancement

#66 Program DLMS actual powers as latent with past date
  primestg/dlms_templates.py
  spec/Order_B12_spec.py
  spec/utils_spec.py
Labels: bug, to be merged

#65 Generate cycle
  primestg/report/base.py
  primestg/report/reports.py
  primestg/utils.py
  setup.py
  spec/Report_S23_spec.py
  spec/data/ZIV0004389874_7_S23_0_20210226020937
Labels: to be merged

#67 FIX DLMS template overwriting
  primestg/order/orders.py
Labels: bug, to be merged

#69 FIX New tariff activation date
  primestg/dlms_templates.py
Labels: enhancement

#68 Add support for sending cycle files to ZIVs
  primestg/cli.py
  primestg/utils.py
  primestg/ziv_service.py
Labels: WIP

#70 FIX contract name reader only printable
  primestg/utils.py
Labels: bug, to be merged
