Repository gisce/primestg, pull requests merged in 2021-05, with the labels that each got.

#72 Fix better date parser (octet2date)
  primestg/utils.py
  spec/Report_S23_spec.py
  spec/data/CIR4621424127_188DE4_S23_0_20210504202212
  spec/utils_spec.py
Labels: bug

#73 Load s23 fixes
  primestg/report/base.py
  primestg/report/reports.py
  primestg/utils.py
  spec/Report_S23_spec.py
  spec/data/S23_bad_date.xml
  spec/data/S23_empty_day.xml
  spec/utils_spec.py
Labels: bug

#74 Imp dlms set name last
  primestg/dlms_templates.py
  spec/Report_S23_spec.py
Labels: enhancement

#76 IMP octet2date improvements
  primestg/report/base.py
  primestg/utils.py
  spec/Report_S23_spec.py
  spec/data/CIR4621816077_59864AC_S23_0_20190514165558_result.txt
  spec/data/S06_empty_datetime.xml_result.txt
  spec/data/ZIV0004488684_59412C2_S23_0_20190424225341_result.txt
  spec/utils_spec.py
Labels: bug, enhancement
