Repository gisce/primestg, pull requests merged in 2024-10, with the labels that each got.

#115 IMP - Add meter group 10 and its subgroup 1
  primestg/event_groups.py
Labels: enhancement, to be merged, patch

#116 Fix requirements py2
  requirements.txt
Labels: patch

#118 FIX - Fix tests
  primestg/report/reports.py
  spec/Order_B02_spec.py
  spec/Order_B07_spec.py
  spec/Report_S01_spec.py
  spec/Report_S21_spec.py
  spec/Report_S26_spec.py
  spec/data/S01.xml_result.txt
  spec/data/S21.xml_result.txt
  spec/data/S21_with_error.xml_result.txt
  spec/data/S26.xml_result.txt
Labels: bug
