Repository gisce/primestg, pull requests merged in 2024-05, with the labels that each got.

#101 IMP - Add event groups 7, 8, & 9
  primestg/utils.py
Labels: to be merged

#102 IMP - Add bad timestamp FFFFFFFFFFFFF79
  primestg/report/base.py
Labels: enhancement, to be merged

#103 ADD long_description to setup
  .bumpversion.cfg
  setup.py
Labels: enhancement, minor
