Repository gisce/primestg, pull requests merged in 2025-01, with the labels that each got.

#128 FIX - remove click from requires
  setup.py
Labels: bug, patch

#129 NEW - Add S26 request
  primestg/service.py
Labels: enhancement, to be merged, minor

#130 NEW Cli commands stgip &ntpip
  primestg/cli.py
Labels: bug, to be merged, patch
